# Generated by Django 4.2.30 on 2026-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='برند')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('persian_name', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('year', models.IntegerField(verbose_name='سال ساخت')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'بنزینی'), ('diesel', 'دیزلی'), ('hybrid', 'هیبریدی'), ('electric', 'الکتریکی')], max_length=50, verbose_name='نوع سوخت')),
                ('transmission', models.CharField(choices=[('automatic', 'اتوماتیک'), ('manual', 'دستی')], max_length=50, verbose_name='گیربکس')),
                ('engine', models.CharField(blank=True, max_length=100, verbose_name='موتور')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت')),
                ('main_image', models.ImageField(upload_to='cars/', verbose_name='تصویر اصلی')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='گالری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('seo_description', models.TextField(blank=True, verbose_name='توضیحات SEO')),
                ('og_image', models.ImageField(blank=True, upload_to='og/cars/', verbose_name='تصویر OG')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'خودرو',
                'verbose_name_plural': 'خودروها',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
