# Generated by Django 4.2.30 on 2026-08-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, unique=True, verbose_name="اسلاگ"
            ),
        ),
    ]
