# Generated by Django 4.2.30 on 2026-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاریخ حذف"),
        ),
        migrations.AddField(
            model_name="car",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="حذف شده"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["brand", "is_active", "is_deleted"],
                name="cars_car_brand_16f091_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["year", "is_active", "is_deleted"],
                name="cars_car_year_d1c6c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["is_featured", "is_active", "is_deleted"],
                name="cars_car_is_feat_eb8dfc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["display_order", "created_at"],
                name="cars_car_display_5076ff_idx",
            ),
        ),
    ]
