# Generated by Django 4.2.30 on 2026-08-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_deleted_at_car_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["fuel_type", "is_active"], name="cars_car_fuel_ty_643376_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["transmission", "is_active"], name="cars_car_transmi_552c7d_idx"
            ),
        ),
    ]
