# Generated by Django 4.2.30 on 2026-08-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_cars_car_fuel_ty_643376_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=200, verbose_name="اسلاگ"
            ),
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("slug",),
                name="car_slug_unique_when_not_deleted",
            ),
        ),
    ]
