# Generated by Django 4.2.30 on 2026-08-28 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_slug_car_car_slug_unique_when_not_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="body_type",
            field=models.CharField(blank=True, max_length=50, verbose_name="نوع بدنه"),
        ),
        migrations.AddField(
            model_name="car",
            name="catalog_file",
            field=models.FileField(
                blank=True,
                help_text="فایل PDF کاتالوگ خودرو",
                null=True,
                upload_to="car_catalogs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="کاتالوگ PDF",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(blank=True, max_length=100, verbose_name="رنگ بدنه"),
        ),
        migrations.AddField(
            model_name="car",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="کشور سازنده"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="technical_description",
            field=models.TextField(
                blank=True,
                help_text="متن یا HTML برای نمایش در تب توضیحات فنی",
                verbose_name="توضیحات فنی",
            ),
        ),
    ]
