# Generated by Django 4.2.30 on 2026-09-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_car_body_type_car_catalog_file_car_color_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="car_active_deleted_idx"
            ),
        ),
    ]
