# Generated by Django 4.2.30 on 2026-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='تصویر')),
                ('alt_text', models.CharField(max_length=300, verbose_name='متن جایگزین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'اسلاید هیرو',
                'verbose_name_plural': 'اسلایدهای هیرو',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('new_path', models.CharField(max_length=500)),
                ('status_code', models.IntegerField(default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='راهنورد خودرو', max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('default_seo_title', models.CharField(blank=True, max_length=200)),
                ('default_seo_description', models.TextField(blank=True)),
                ('default_og_image', models.ImageField(blank=True, upload_to='og/')),
                ('hero_cta_primary_text', models.CharField(default='مشاهده خودروها', max_length=100, verbose_name='متن دکمه اصلی هیرو')),
                ('hero_cta_primary_link', models.CharField(default='#cars', max_length=200, verbose_name='لینک دکمه اصلی')),
                ('hero_cta_secondary_text', models.CharField(default='درخواست مشاوره', max_length=100, verbose_name='متن دکمه فرعی هیرو')),
                ('hero_cta_secondary_link', models.CharField(default='#consult', max_length=200, verbose_name='لینک دکمه فرعی')),
                ('why_title', models.CharField(default='چرا راهنورد خودرو؟', max_length=200, verbose_name='عنوان بخش چرا ما')),
                ('why_description', models.TextField(default='راهنورد خودرو با تمرکز بر واردات خودروهای روز دنیا، تلاش می\u200cکند تجربه\u200cای مطمئن، شفاف و حرفه\u200cای در خرید خودروهای وارداتی برای مشتریان خود فراهم کند.', verbose_name='توضیحات بخش چرا ما')),
                ('cars_section_title', models.CharField(default='خودروهای ما', max_length=200, verbose_name='عنوان بخش خودروها')),
                ('cars_section_description', models.TextField(default='مجموعه\u200cای منتخب از خودروهای وارداتی راهنورد خودرو، آماده تحویل با گارانتی رسمی.', verbose_name='توضیحات بخش خودروها')),
                ('articles_section_title', models.CharField(default='مقاله و اطلاعیه', max_length=200, verbose_name='عنوان بخش مقالات')),
                ('articles_section_description', models.TextField(default='آخرین اخبار، اطلاعیه\u200cها و راهنماهای خرید خودرو را دنبال کنید.', verbose_name='توضیحات بخش مقالات')),
                ('branches_section_title', models.CharField(default='شعب راهنورد خودرو', max_length=200, verbose_name='عنوان بخش شعب')),
                ('form_title', models.CharField(default='درخواست خود را برای ما ارسال نمایید', max_length=200, verbose_name='عنوان فرم مشاوره')),
                ('form_description', models.TextField(default='همکاران ما در کوتاه\u200cترین زمان ممکن با شما تماس خواهند گرفت.', verbose_name='توضیحات فرم مشاوره')),
                ('footer_description', models.TextField(default='راهنورد خودرو ، واردکننده رسمی خودروهای هیوندای، کیا و تویوتا با بیش از یک دهه تجربه در خدمت مشتریان.', verbose_name='توضیحات فوتر')),
                ('footer_copyright', models.CharField(default='راهنورد خودرو. تمامی حقوق محفوظ است.', max_length=200, verbose_name='متن کپی\u200cرایت')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='WhyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, upload_to='features/', verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'ویژگی چرا ما',
                'verbose_name_plural': 'ویژگی\u200cهای چرا ما',
                'ordering': ['display_order'],
            },
        ),
    ]
