# Generated by Django 4.2.30 on 2026-08-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="لینک صفحه مقصد (مثلاً /cars/toyota-rav4 یا /#consult)",
                max_length=500,
                verbose_name="لینک",
            ),
        ),
    ]
