# Generated by Django 4.2.30 on 2026-08-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_link_to_heroslide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_cta_primary_link",
            field=models.CharField(
                default="/cars", max_length=200, verbose_name="لینک دکمه اصلی"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_cta_secondary_link",
            field=models.CharField(
                default="/#consult", max_length=200, verbose_name="لینک دکمه فرعی"
            ),
        ),
    ]
