# Generated by Django 4.2.30 on 2026-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_hero_cta_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='why_background',
            field=models.ImageField(blank=True, upload_to='why/', verbose_name='تصویر پس\u200cزمینه بخش چرا ما'),
        ),
    ]
