# Generated by Django 4.2.30 on 2026-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('cover_image', models.ImageField(blank=True, upload_to='articles/', verbose_name='تصویر کاور')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('seo_description', models.TextField(blank=True, verbose_name='توضیحات SEO')),
                ('og_image', models.ImageField(blank=True, upload_to='og/articles/', verbose_name='تصویر OG')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
