# Generated by Django 4.2.30 on 2026-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاریخ حذف"),
        ),
        migrations.AddField(
            model_name="article",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="حذف شده"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_published", "published_at", "is_deleted"],
                name="articles_ar_is_publ_b812cd_idx",
            ),
        ),
    ]
