# Generated by Django 4.2.30 on 2026-08-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_deleted_at_article_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=300, verbose_name="اسلاگ"
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("slug",),
                name="article_slug_unique_when_not_deleted",
            ),
        ),
    ]
