# Generated by Django 4.2.30 on 2026-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاریخ حذف"),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="حذف شده"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["is_read", "created_at"], name="inquiries_i_is_read_f03164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["is_contacted", "created_at"],
                name="inquiries_i_is_cont_68b35e_idx",
            ),
        ),
    ]
