# Generated by Django 4.2.30 on 2026-08-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0002_inquiry_deleted_at_inquiry_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inquiry",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="inquiry",
            name="user_agent",
        ),
    ]
