# Generated by Django 4.2.30 on 2026-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="تاریخ حذف"),
        ),
        migrations.AddField(
            model_name="branch",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="حذف شده"
            ),
        ),
    ]
