# Generated by Django 4.2.30 on 2026-08-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_branch_deleted_at_branch_is_deleted"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="branches_br_is_acti_eb2220_idx",
            ),
        ),
    ]
